<?php

class Card extends DBHandler{
    protected $sqlFilePath = "sql/cards.json";
    protected $tableName = "Card";

    private $pk;
    private $uid;
    private $cardType;
    private $generated;
    private $deck;
    private $owner;

    public function get_pk(){
        return $this->pk;
    }

    public function get_uid(){
        return $this->uid;
    }

    public function get_image_path(){
        return $this->cardType->get_image_path();
    }

    public function get_card_type(){
        return $this->cardType;
    }

    public function is_generated(){
        return $this->generated;
    }

    public function get_deck(){
        return $this->deck;
    }

    public function get_owner(){
        return $this->owner;
    }

    public function get_type_name(){
        return $this->cardType->get_name();
    }

    public function get_type_action_str(){
        return $this->cardType->get_actions_str();
    }

    public function set_card_from_database($pk, $user){
        $query = "SELECT * FROM Card WHERE pk = ? AND characterId = ?";
        $values = array($pk, $user->get_uid());
        $types = array("ii");
        $result = $this->execute_query($query, $values, $types);
        if($result->num_rows > 0){
            $row = $result->fetch_assoc();
            $this->set_card_from_query($row, $user);
        }
    }

    private function insert_card(){
        $query = "INSERT INTO Card (uid, cardType, characterId, autoGenerated) VALUES (?, ?, ?, ?);";
        $values = array($this->uid, $this->cardType->get_pk(), $this->owner->get_uid(), $this->generated);
        $types = array("i", "i", "i", "i");
        $this->execute_query($query, $values, $types);
        return $this->pk = $this->get_last_insert_id();
    }

    public function create_new_auto_card($user, $cardType){
        $this->uid = -1;
        $this->cardType = new CardType($cardType);
        $this->owner = $user;
        $this->generated = True;
        $this->insert_card();
    }

    public function set_card_from_query($row, $user){
        $this->pk = $row["pk"];
        $this->uid = $row["uid"];
        $this->cardType = new CardType($row["cardType"]);
        $this->generated = $row["autoGenerated"];
        $this->deck = $row["deck"];
        $this->owner = $user;
    }

    public function populate_from_query($pk, $character, $cardType, $generated){
        $this->pk = $pk;
        $this->owner = $character;
        $this->cardType = new CardType($cardType);
        $this->generated = $generated;
    }

    public function add_to_deck($deckId){
        $this->deck = $deckId;
        $query = "UPDATE Card SET deck = ? WHERE pk = ?;";
        $values = array($this->deck, $this->pk);
        $types = array("ii");
        $this->execute_query($query, $values, $types);
    }

    public function remove_from_deck(){
        $this->deck = NULL;
        $query = "UPDATE Card SET deck = NULL WHERE pk = ?;";
        $values = array($this->pk);
        $types = array("i");
        $this->execute_query($query, $values, $types);
    }

    public function __construct(){
        $this->database_setup();
    }
}