<?php

require_once "includes/cardtypes.php";

function generate_cards($user, $num){
    $deck = New Deck();    
    if(!$deck->get_deck_by_name("Starter Deck", $user)){
        $deck->create_new_deck("Starter Deck", $user);
    }
    while ($num < 10){
        $card = New Card();
        $cardType = get_random_type();
        $card->create_new_auto_card($user, $cardType, $deck->get_pk());
        $deck->add_card($card);
        $num += 1;
    }
}

function card_check($user){
    $db = new DBHandler();
    $query = "SELECT * from Card WHERE characterId = ?;";
    $values = array($user->get_uid());
    $types = array("i");
    $results = $db->execute_query($query, $values, $types);
    if($results->num_rows < 10){
        generate_cards($user, $results->num_rows);
    } 
    
}

function card_list($user, $generated = False){
    $db = new DBHandler();
    $query = "SELECT * from Card WHERE characterId = ? and autoGenerated = 0;";
    if($generated){
        $query = "SELECT * from Card WHERE characterId = ? and autoGenerated = 1;";
    }
    $values = array($user->get_uid());
    $types = array("i");
    $results = $db->execute_query($query, $values, $types);
    $cards = array();
    while($row = $results->fetch_assoc()){
        $card = New Card();
        $card->set_card_from_query($row, $user);
        array_push($cards, $card);
    }
    return $cards;
}

function get_deck($card){
    $deck = New Deck();
    $deck->get_deck_by_pk($card->get_deck());
    return  $deck;
}

function card_count($user, $generated=False){
    $db = new DBHandler();
    $query = "SELECT * from Card WHERE characterId = ? AND autoGenerated = 0;";
    if($generated){
        $query = "SELECT * from Card WHERE characterId = ? AND autoGenerated = 1;";
    }
    $values = array($user->get_uid());
    $types = array("i");
    $results = $db->execute_query($query, $values, $types);
    return $results->num_rows;
}